'use client'

import React from 'react'
import styled from 'styled-components'
import Logo from '@/sanity/components/Logo'

// 1. DEFINE THE PROPS INTERFACE
// Sanity automatically passes these props to your custom login component
interface LoginProps {
  providers?: {
    name: string
    title: string
    url: string // <--- THIS IS THE KEY! It contains the secure login link with state
  }[]
}

// Reuse the Premium Dark Theme Styled Components
const PageContainer = styled.div`
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #121212;
  font-family: 'Inter', sans-serif;
  
  /* Ensure it sits on top if invoked within Studio layout */
  position: relative;
  z-index: 1000;
`

const LoginCard = styled.div`
  width: 100%;
  max-width: 460px;
  padding: 56px;
  background-color: #1E1E1E;
  border-radius: 20px;
  border: 1px solid #333;
  box-shadow: 0 40px 80px -15px rgba(0, 0, 0, 0.7), 0 0 0 1px rgba(255, 255, 255, 0.05);
  display: flex;
  flex-direction: column;
  align-items: center;
  position: relative;
  z-index: 10;
  backdrop-filter: blur(10px);
`

const Title = styled.div`
  margin-top: 24px;
  margin-bottom: 32px;
  text-align: center;
  
  h1 {
    color: #fff;
    font-size: 1.5rem;
    font-weight: 700;
    margin-bottom: 8px;
  }
  
  p {
    color: #888;
    font-size: 1rem;
  }
`

const AuthButton = styled.button`
  width: 100%;
  padding: 16px;
  border-radius: 12px;
  font-size: 1.05rem;
  font-weight: 600;
  text-decoration: none;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  transition: transform 0.2s, box-shadow 0.2s, background-color 0.2s;
  border: none;
  margin-bottom: 16px;

  &:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.3);
  }
`

const GoogleButton = styled(AuthButton)`
  background-color: #fff;
  color: #1f1f1f;
  border: 1px solid #e0e0e0;
`

const EmailButton = styled(AuthButton)`
  background-color: #3B82F6;
  color: #fff;
  border: 1px solid #3B82F6;
  
  &:hover {
    background-color: #2563EB;
  }
`

const Divider = styled.div`
  display: flex;
  align-items: center;
  width: 100%;
  margin: 24px 0;
  color: #666;
  
  &::before, &::after {
    content: '';
    flex: 1;
    height: 1px;
    background: #333;
  }
  
  span {
    padding: 0 12px;
    font-size: 0.9rem;
  }
`

// 2. ACCEPT PROPS IN THE FUNCTION
export default function CustomLogin(props: LoginProps) {
  // We don't need useWorkspace here anymore, we use the props provided by Sanity

  const handleLogin = (providerName: string) => {
    // 3. FIND THE CORRECT URL FROM PROPS
    // This URL is generated by Sanity and includes the secure 'State' token you were missing!
    const provider = props.providers?.find((p) => p.name === providerName)
    
    if (provider?.url) {
      window.location.href = provider.url
    } else {
      console.error(`Provider '${providerName}' not found in Sanity configuration.`)
    }
  }

  return (
    <PageContainer>
      <LoginCard>
         <div style={{ marginBottom: '20px' }}>
            <Logo />
         </div>
         
         <Title>
            <h1>Admin Portal</h1>
            <p>Sign in to manage PulseQuik</p>
         </Title>

         <GoogleButton onClick={() => handleLogin('google')}>
            <svg width="20" height="20" viewBox="0 0 24 24">
                <path fill="#EA4335" d="M12 5.04c3.27 0 6.22 1.13 8.54 3.19l6.29-6.29C22.69 1.54 17.38 0 12 0 7.37 0 3.32 2.68 1.63 6.64l7.14 5.92C9.46 9.38 10.66 5.04 12 5.04z" />
                <path fill="#34A853" d="M12 24c5.96 0 10.87-4.14 12.63-9.59H12v-7.2h8.8c.8 4.29.35 8.79-2.2 12.39-2.58 3.65-6.66 5.6-11.2 5.6-6.17 0-11.66-3.8-13.88-9.4l-7.16 6.04C3.21 21.02 7.37 24 12 24z" />
                <path fill="#4A90E2" d="M24 12.2c0-.86-.06-1.68-.19-2.48H12v4.8h6.84c-.3 1.51-1.16 2.76-2.4 3.76l5.7 4.54c3.35-3.09 5.25-7.61 5.25-12.2" />
                <path fill="#FBBC05" d="M1.63 6.64l-1.3-3.69L.29 .29C-1.87 4.14 -1.87 8.57 .29 12.42l3.29-2.61 1.76-1.5c-1.35-2.27-1.35-4.99 0-7.27l-3.71-3.08" />
                <path fill="#34A853" d="M0 12c0 3.96 1.41 6.84 3.71 9.36L10.87 15.35c-2.25-1.55-3.68-4.08-3.68-7.35 0-3.27 1.43-5.8 3.68-7.35L3.71 0C1.41 2.52 0 5.4 0 9.36" />
                <path fill="#EA4335" d="M12 5.04c3.27 0 6.22 1.13 8.54 3.19l6.29-6.29C22.69 1.54 17.38 0 12 0 7.37 0 3.32 2.68 1.63 6.64l7.14 5.92C9.46 9.38 10.66 5.04 12 5.04z" />
            </svg>
            Sign in with Google
         </GoogleButton>

         <Divider><span>OR</span></Divider>

         {/* Use 'sanity' or 'email' depending on how your provider is named in config */}
         <EmailButton onClick={() => handleLogin('sanity')}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="2" y="4" width="20" height="16" rx="2" />
                <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
            </svg>
            Sign in with Email
         </EmailButton>

      </LoginCard>
    </PageContainer>
  )
}
